#!/bin/bash

# In this configuration, the following dependent libraries are compiled:
#
# * zlib
# * c-ares
# * expat
# * sqlite3
# * openSSL
# * libssh2

#COMPILER AND PATH
PREFIX=/opt/aria2/build_libs
C_COMPILER="gcc"
CXX_COMPILER="g++"

#CHECK TOOL FOR DOWNLOAD
 aria2c --help > /dev/null
 if [ "$?" -eq 0 ] ; then
   DOWNLOADER="aria2c --check-certificate=false"
 else
   DOWNLOADER="wget -c"
 fi

## DEPENDENCES ##
ZLIB=http://sourceforge.net/projects/libpng/files/zlib/1.2.11/zlib-1.2.11.tar.gz
OPENSSL=http://www.openssl.org/source/openssl-1.0.2o.tar.gz
EXPAT=https://sourceforge.net/projects/expat/files/expat/2.2.0/expat-2.2.0.tar.bz2
SQLITE3=http://www.sqlite.org/2018/sqlite-autoconf-3230100.tar.gz
C_ARES=http://c-ares.haxx.se/download/c-ares-1.14.0.tar.gz
SSH2=https://www.libssh2.org/download/libssh2-1.7.0.tar.gz

## CONFIG ##
BUILD_DIRECTORY=/tmp/

## BUILD ##
cd $BUILD_DIRECTORY
#
 # zlib build
  [ ! -f "/tmp/.zlib" ] && $DOWNLOADER $ZLIB

  tar zxvf zlib-1.2.11.tar.gz && touch "/tmp/.zlib"
  if [ ! -f "/tmp/.zlib_installed" ];then
    cd zlib-1.2.11/
    PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --prefix=$PREFIX --static
    make -j`grep -c ^processor /proc/cpuinfo`
    make install
    cd ..
    touch "/tmp/.zlib_installed";
  fi
#
 # expat build
  [ ! -f "/tmp/.expat" ] && $DOWNLOADER $EXPAT
  tar jxvf expat-2.2.0.tar.bz2 && touch "/tmp/.expat"
  if [ ! -f "/tmp/.expat_installed" ];then
    cd expat-2.2.0/
    PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --prefix=$PREFIX --enable-static --enable-shared
    make -j`grep -c ^processor /proc/cpuinfo`
    make install
    cd ..
    touch "/tmp/.expat_installed";
  fi
#
 # c-ares build
  [ ! -f "/tmp/.c-ares" ] && $DOWNLOADER $C_ARES
  tar zxvf c-ares-1.14.0.tar.gz && touch "/tmp/.c-ares"
  if [ ! -f "/tmp/.c-ares_installed" ];then
    cd c-ares-1.14.0/
    PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --prefix=$PREFIX --enable-static --disable-shared
    make -j`grep -c ^processor /proc/cpuinfo`
    make install
    cd ..
    touch "/tmp/.c-ares_installed";
  fi
#
 # Openssl build
  [ ! -f "/tmp/.openssl" ] && $DOWNLOADER $OPENSSL
  tar zxvf openssl-1.0.2o.tar.gz && touch "/tmp/.openssl"
  if [ ! -f "/tmp/.openssl_installed" ];then
    cd openssl-1.0.2o/
    PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./Configure --prefix=$PREFIX linux-x86_64 shared
    make -j`grep -c ^processor /proc/cpuinfo`
    make install
    cd ..
    touch "/tmp/.openssl_installed";
  fi
#
 # sqlite3
  [ ! -f "/tmp/.sqlite" ] && $DOWNLOADER $SQLITE3
  tar zxvf sqlite-autoconf-3230100.tar.gz && touch "/tmp/.sqlite"
  if [ ! -f "/tmp/.sqlite_installed" ];then
    cd sqlite-autoconf-3230100/
    PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --prefix=$PREFIX --enable-static --enable-shared
    make -j`grep -c ^processor /proc/cpuinfo`
    make install
    cd ..
    touch "/tmp/.sqlite3_installed";
  fi
#
 # libssh2
  [ ! -f "/tmp/.libssh2" ] && $DOWNLOADER $SSH2
  tar zxvf libssh2-1.7.0.tar.gz && touch "/tmp/.libssh2"
  if [ ! -f "/tmp/.libssh2_installed" ];then
    cd libssh2-1.7.0/
    rm -rf $PREFIX/lib/pkgconfig/libssh2.pc
    PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --without-libgcrypt --with-openssl --without-wincng --prefix=$PREFIX --enable-static --disable-shared
    make -j`grep -c ^processor /proc/cpuinfo`
    make install
    cd ..
    touch "/tmp/.libssh2_installed";
  fi
#
 #cleaning
  rm -rf `ls |grep c-ares|grep -v tar`
  rm -rf `ls |grep sqlite-autoconf|grep -v tar`
  rm -rf `ls |grep zlib-|grep -v tar`
  rm -rf `ls |grep expat-|grep -v tar`
  rm -rf `ls |grep openssl-|grep -v tar`
  rm -rf `ls |grep libssh2-|grep -v tar`
#
 echo "finished!"
