#!/bin/sh

set -eux

# In this configuration, the following dependent libraries are compiled:
#
# * zlib
# * c-ares
# * expat
# * sqlite3
# * openSSL
# * libssh2

#COMPILER AND PATH
PREFIX=/usr
C_COMPILER="gcc"
CXX_COMPILER="g++"

#CHECK TOOL FOR DOWNLOAD
 aria2c --help > /dev/null
 if [ "$?" -eq 0 ] ; then
   DOWNLOADER="aria2c --check-certificate=false"
 else
   DOWNLOADER="wget -c"
 fi

## DEPENDENCES ##
ZLIB=http://sourceforge.net/projects/libpng/files/zlib/1.2.11/zlib-1.2.11.tar.gz
OPENSSL=http://www.openssl.org/source/openssl-1.1.1g.tar.gz
EXPAT=https://github.com/libexpat/libexpat/releases/download/R_2_2_9/expat-2.2.9.tar.bz2
SQLITE3=https://sqlite.org/2020/sqlite-autoconf-3310100.tar.gz
C_ARES=http://c-ares.haxx.se/download/c-ares-1.16.0.tar.gz
SSH2=https://www.libssh2.org/download/libssh2-1.9.0.tar.gz

## CONFIG ##
BUILD_DIRECTORY=/tmp/

## BUILD ##
cd $BUILD_DIRECTORY
#
 # zlib build
  [ ! -f zlib-1.2.11.tar.gz ] && $DOWNLOADER $ZLIB
  tar zxvf zlib-1.2.11.tar.gz
  cd zlib-1.2.11/
  PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --prefix=$PREFIX --static
  make
  make install
#
 # expat build
  cd ..
  [ ! -f expat-2.2.9.tar.bz2 ] && $DOWNLOADER $EXPAT
  tar jxvf expat-2.2.9.tar.bz2
  cd expat-2.2.9/
  PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --prefix=$PREFIX --enable-static --enable-shared
  make
  make install
#
 # c-ares build
  cd ..
  [ ! -f c-ares-1.16.0.tar.gz ] && $DOWNLOADER $C_ARES
  tar zxvf c-ares-1.16.0.tar.gz
  cd c-ares-1.16.0/
  PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --prefix=$PREFIX --enable-static --disable-shared
  make
  make install
#
 # Openssl build
  cd ..
  [ ! -f openssl-1.1.1g.tar.gz ] && $DOWNLOADER $OPENSSL
  tar zxvf openssl-1.1.1g.tar.gz
  cd openssl-1.1.1g/
  wget https://git.alpinelinux.org/aports/plain/main/openssl/CVE-2019-1551.patch
  wget https://git.alpinelinux.org/aports/plain/main/openssl/man-section.patch
  patch -p1 < CVE-2019-1551.patch
  patch -p1 < man-section.patch
  PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./Configure linux-x86_64 --prefix=$PREFIX --libdir=lib --openssldir=$PREFIX/etc/ssl shared no-zlib enable-ec_nistp_64_gcc_128 no-async no-comp no-idea no-mdc2 no-rc5 no-ec2m no-sm2 no-sm4 no-ssl2 no-ssl3 no-seed no-weak-ssl-ciphers $CPPFLAGS $CFLAGS $LDFLAGS -Wa,--noexecstack
  make
  make install
#
 # sqlite3
  cd ..
  [ ! -f sqlite-autoconf-3310100.tar.gz ] && $DOWNLOADER $SQLITE3
  tar zxvf sqlite-autoconf-3310100.tar.gz
  cd sqlite-autoconf-3310100/
  PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --prefix=$PREFIX --enable-static --enable-shared
  make
  make install
#
 # libssh2
  cd ..
  [ ! -f libssh2-1.9.0.tar.gz ] && $DOWNLOADER $SSH2
  tar zxvf libssh2-1.9.0.tar.gz
  cd libssh2-1.9.0/
  rm -rf $PREFIX/lib/pkgconfig/libssh2.pc
  PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ LD_LIBRARY_PATH=$PREFIX/lib/ CC="$C_COMPILER" CXX="$CXX_COMPILER" ./configure --without-libgcrypt --with-openssl --without-wincng --prefix=$PREFIX --enable-static --disable-shared
  make
  make install
#
 #cleaning
  cd ..
  # rm -rf c-ares*
  # rm -rf sqlite-autoconf*
  # rm -rf zlib-*
  # rm -rf expat-*
  # rm -rf openssl-*
  # rm -rf libssh2-*
#
 echo "finished!"
