#
# This is free software, lisence use MIT.
#
# based on work form Copyright (C) 2020 tofuliang <tofuliang@gmail.com>
#

name: aria2_x86_64-Static-link-on-started

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #- name: 校验本地文件
      - uses: actions/checkout@master
        with:
          ref: master
      - name: download and install docker-composer
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-`uname -s`-`uname -m` > docker-compose
          sudo chmod +x docker-compose
          ./docker-compose up -d
      - name: Compiler run
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker exec docker_build_aria2_311 sh build-scripts/gnu-linux-config/build.sh
          docker cp docker_build_aria2_311:/tmp/aria2-1.35.0/src/aria2c ./
      - name: clean-up not needed artifacts
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          mv aria2c* ./artifact/
      - name : upload-artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.name }}-name
          path: ${{ github.workspace }}/artifact/**/*
