# This is a basic workflow to help you get started with Actions

name: aria2_x86_64-Static-link-on-push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
         path: |
           /home/runner/.ccache
           ~/cache
           !~/cache/exclude
           **/node_modules
           ~/.ccache
           **/.ccache
         # https://github.com/azerothcore/azerothcore-wotlk/blob/master/.github/workflows/core_build.yml
         key: ccache:${{ matrix.os }}:${{ matrix.compiler }}:${{ matrix.modules }}-modules:${{ github.ref }}:${{ github.sha }}
         restore-keys: |
           ccache:${{ matrix.os }}:${{ matrix.compiler }}:${{ matrix.modules }}-modules:${{ github.ref }}
           ccache:${{ matrix.os }}:${{ matrix.compiler }}:${{ matrix.modules }}-modules
# ##key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: installation docker-composer
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > docker-compose
          sudo chmod +x docker-compose
          ./docker-compose up -d
      - name: Compile
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker exec docker_build_aria2_311 sh build-scripts/gnu-linux-config/build.sh
          docker cp docker_build_aria2_311:/tmp/aria2-1.35.0/src/aria2c ./
          docker cp docker_build_aria2_311:/tmp/aria2-1.35.0/src/aria2c-* ./
      - name: clean-up
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          mv aria2c ./artifact/
          mv aria2c-* ./artifact/
      - name : upload-artifact
        uses: actions/upload-artifact@master
        with:
          name: aria2c
          path: ./artifact/
